#------------------- linter -------------------------

# https://docs.astral.sh/ruff/configuration/
[tool.ruff]
exclude = ["*_pb2.py", "*_pb2_*"]
#indent-width = 4
#line-length = 100

[tool.ruff.format]
exclude = ["*.pyi", "*.ipynb"]
[tool.ruff.lint]
ignore = ["F401", "F541", "F841"]
